CREATE SCHEMA FLORICULTURA;

USE FLORICULTURA;

CREATE TABLE ENDERECO
(
	ID_ENDERECO INT NOT NULL PRIMARY KEY,
    CEP CHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL
);

CREATE TABLE CLIENTE
(
	CPF CHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    ID_ENDERECO INT,
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE TELEFONE
(
	ID_TELEFONE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DDD CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(45) NOT NULL,
    CPF CHAR(11),
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);

CREATE TABLE PRODUTO
(
	ID_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    TIPO VARCHAR(45) NOT NULL,
    PRECO_UNITARIO DECIMAL(6,2)  NOT NULL,
    QTD INT NOT NULL
);

CREATE TABLE ENCOMENDA
(
	ID_ENCOMENDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_ENCOMENDA DATETIME NOT NULL,
    STATUS_ENCOMENDA VARCHAR(45) NOT NULL,
    CPF CHAR(11),
    ID_ENDERECO INT,
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE COMANDA
(
	ID_COMANDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QTD_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DECIMAL(6,2) NOT NULL,
    ID_ENCOMENDA INT,
    ID_PRODUTO INT,
    FOREIGN KEY (ID_ENCOMENDA) REFERENCES ENCOMENDA(ID_ENCOMENDA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);




























